### ISSUE TITLE
Month view

### ISSUE THREAD

**Issue by moleroveiss** [jonathantribouharet/JTCalendar#105]
I have a problem with the month view. The calendar shows 6 weeks but if the first day is sunday, i can´t see the first day in this month. 
I also attach you an image.
Do you know what i did wrong?
Best regards
![captura de pantalla 2015-03-30 a la s 17 14 13 1](https://cloud.githubusercontent.com/assets/11721993/6899589/e4f30928-d701-11e4-8e2a-2902d0cd101f.png)

**Comment by jonathantribouharet** [comment]
I don't understand your problem.
On your image the first day of the week is Monday, if you want to begin the week to Sunday you have to do `self.calendar.calendarAppearance.calendar.firstWeekday = 1;` Check the Example project or the README.
Also the calendar always show 6 weeks (because some months need 6 weeks for be display) and it's too complex to manae a calendar with a dynamic height.

**Comment by moleroveiss** [comment]
Ok, I explain you. 
When i put these lines in my code: 
      NSLocale *locale = [NSLocale localeWithLocaleIdentifier:@"es_ES"];
      self.calendar.calendarAppearance.calendar.locale = locale;
The calendar show wrong the days of the month, but if I change this line to @"en_EN", the calendar works perfectly. Do you have any idea?
Thanks!

**Comment by jonathantribouharet** [comment]
I see the bug, I don't know why it happen but from what I understand about NSCalendar when you use `firstWeekday` it overrides `locale` and `locale` is not used to translate the days or the month, so I only can advise don't set locale.

**Comment by jonathantribouharet** [comment]
I just release a new version.
Check the Example project.

This bug should be gone.
