### ISSUE TITLE
Event Dot issue

### ISSUE THREAD

**Issue by safyan** [jonathantribouharet/JTCalendar#113]
Hi Dear,
i want to add event dot to my specific date. i can't understand how to add a dot on specific date because u are adding a event dot using rand method and it is calling 210 times when i scroll it right to left in month view.i can't understand the logic Please help me about this?

Thanks in advance.

**Comment by jonathantribouharet** [comment]
It's simple your delegate (your controller I suppose) have to implement the method `calendarHaveEvent`.
This method receive an argument date, if at this date you want a dot return `YES` else return `NO`.
I used a rand in the Example because I wanna display a lot of dots in the calendar but it's just a demo, there is no logic behind the Example.
