### ISSUE TITLE
I select day19 but the log is day18

### ISSUE THREAD

**Issue by malaimoo** [jonathantribouharet/JTCalendar#120]
It log the past day......

**Comment by steilerDev** [comment]
Since this is a very vague problem I am not very sure what you mean, but if you are just printing out the `NSDate` provided by the `calendarDidDateSelected` function of the `JTCalendarDataSource` delegate you have to watch out your time zone. By default NSDate's `description` variable of the `Printable` protocol converts the date to CET, which means if you are in a timezone like Berlin (GMT +1) it will print out `2014-11-29 23:00:00 +0000` even though you selected the 30th of November. 

Concluding this is not a bug but a general problem of date handling that you need to solve by your application. If I got your problem wrong feel free to specify it more accurate.

**Comment by sendoa** [comment]
If you log the date using `[NSDateFormatter localizedStringFromDate:date dateStyle:NSDateFormatterMediumStyle timeStyle:NSDateFormatterShortStyle]` you'll see that @steilerDev is OK ;-)

**Comment by jonathantribouharet** [comment]
Don't rely on [date description] which NSLog uses, it takes into account your local timezone, use NSDateFormatter.
