### ISSUE TITLE
ld: library not found for -lPods-JTCalendar   

### ISSUE THREAD

**Issue by huangyunjin** [jonathantribouharet/JTCalendar#128]
how   to   solve  it  ,thanks!

**Comment by jonathantribouharet** [comment]
Sorry but this problem is more related to cocoapod than my lib. I suggest you search more info on stackoverflow. I can only advise you to do a `pod update` and clean your project but it's not very helpful.
With a quick search on google I found this http://stackoverflow.com/questions/9863836/library-not-found-for-lpods.
Good luck.
