### ISSUE TITLE
Paging/Scrolling prepareDayView slow

### ISSUE THREAD

**Issue by jonandersen** [jonathantribouharet/JTCalendar#168]
I'm having an issue where my `prepareDayView` is somewhat slow. For each call inside the 
 `prepareDayView` i make query to fetch the count of videos for that day. 
`PHAsset.fetchAssetsWithMediaType(.Video, options: options).count` This query is somewhat slow and it results in the paging feeling sluggish since it has to wait for the query to return (takes about 0.3 seconds for all 30 days to be computed). I notice that the method is called when the page is about to be displayed . Is there any way I can render that page before the scrolling to it kicks in? That is having the next & previous page rendered as well as the current. 

Thanks for a great library!

**Comment by jonathantribouharet** [comment]
The method is called each time the current page changed (if you want change something related to the current page).
I think the best thing you can do is create a cache, I mean preload the count of video and use this cache in `prepareDayView`. You could load 5 pages and each time `calendarDidLoadNextPage` or `calendarDidLoadPreviousPage` is called, load the new page asynchronously (in another thread, width dispatch_async).

**Comment by jonandersen** [comment]
@jonathantribouharet Thanks, I'll check that out!

**Comment by jonandersen** [comment]
I found a simple way to speed it up that works. Hopefully it can be of use to someone (I'm using 
https://github.com/duemunk/Async but it's just a wrapper for GCD) 
```
 func calendar(calendar: JTCalendarManager!, prepareDayView dayView: UIView!) {
	if(self.cache[day.date] != nil){
	    self.colorCircle(day)
	}else{
	    Async.background{
	        self.cache[day.date] = self.mediaManager.getMedia(day.date).count 
	    }.main{
	        self.colorCircle(day) 
	    }
	}
}

func colorCircle(day: JTCalendarDayView) {
    if(self.cache[day.date] > 0){
        day.circleView.backgroundColor = UIColor.orangeColor()
        day.textLabel.textColor = UIColor.whiteColor()
    }else{
        day.circleView.hidden = true
        day.textLabel.textColor = UIColor.blackColor()
    }
}
    
```

**Comment by jonathantribouharet** [comment]
Your method is good but have one problem.
Imagine the method `prepareDayView` is call on a dayView, the cache is empty and the async loading is started, just after you slide one page, so the same dayView will be reload with a new date, imagine at this moment the async loading is not done yet and the cache for the new date is not empty.
The dayView will change the color for the new date instantly, because the data is in the cache, and after the async task will end and update the dayView with the result of the old date!
It may seem complicated or a very rare case, but add a `sleep(1000)` in `Async.background` and you will see the problem.
But your task take only 0.3 so I don't think you will have this problem but keep in mind if you have something slower than this, you may have a problem, specially if you slide quickly a lot of pages.
