### ISSUE TITLE
Vertical layout miss some days at the beginning or the and of the month

### ISSUE THREAD

**Issue by DrAma999** [jonathantribouharet/JTCalendar#172]
Vertical layout, english locale, but applies also with italian. A lot of times it misses the first day of the month or the last days.   Tested only on simulator, iOS8, Xcode 6.4. Here is a screen:
![ios simulator screen shot 21 lug 2015 09 08 01](https://cloud.githubusercontent.com/assets/958522/8794921/6fdfd3e8-2f88-11e5-9859-4872a160a70e.png)

**Comment by DrAma999** [comment]
I've run few tests to help you understanding the issue. The problem of hidden says is just a matter of visualization in the sample code. If I put in the VerticalViewController, in the delegate method -calendar:prepareDayView: a dayView.hidden= NO before everything views are visible again probably is because you are reciclying them. Maybe a -prepareForReuse in the CalendarView can be helpfull.
What I've noticed though is that sometimes complete lines of first days are not displayed as they are "paged" in the month before.

**Comment by jonathantribouharet** [comment]
I'm on it, I had the same process, first I think the problem was from `samemonth` and currently I see the variable  `IsFromAnotherMonth` is not good.
Yes I reuse the view (the performance are not good so I try to optimise). I keep you inform, you were not the first to notice this bug, but the first person was on a Chinese version so I thought it was coming from the timezone or the locale...

**Comment by jonathantribouharet** [comment]
I found the bug, it's very stupid. I don't reinitialize `hidden` in `prepareDayView` just change the method:

	// Exemple of implementation of prepareDayView method
	// Used to customize the appearance of dayView
	- (void)calendar:(JTCalendarManager *)calendar prepareDayView:(JTCalendarDayView *)dayView
	{
	    dayView.hidden = NO; // <--- Add this line
	    
	    // Hide if from another month
	    if([dayView isFromAnotherMonth]){
	        dayView.hidden = YES;
	    }

**Comment by DrAma999** [comment]
Exactly... but there is still another issue even if you fix that one it remains. It seems to appear only in vertical layout. *What I've noticed though is that sometimes complete lines of first days are not displayed as they are "paged" in the month before.*

**Comment by DrAma999** [comment]
![ios simulator screen shot 21 lug 2015 09 08 01](https://cloud.githubusercontent.com/assets/958522/8797102/a31f0c54-2f99-11e5-900f-bc23fb472f5b.png)

**Comment by DrAma999** [comment]
![ios simulator screen shot 21 lug 2015 11 14 08](https://cloud.githubusercontent.com/assets/958522/8797106/ae285eca-2f99-11e5-8c42-a4248ba0204f.png)

**Comment by jonathantribouharet** [comment]
In appear only in vertical layout because only the vertical tab and custom tab hide the day not display in the current month and I didn't forget to reinitialise hidden in the custom tab.

For the other problem, tell me what locale and timeZone you use.
If you use the default from your phone use:

    NSLog(@"%@ - %@", _calendarManager.dateHelper.calendar.timeZone, _calendarManager.dateHelper.calendar.locale.localeIdentifier);

**Comment by DrAma999** [comment]
Thanks, for the explanation. It happens both in english and Italian, just scroll down few months

**Comment by jonathantribouharet** [comment]
It's fixed, update your pod.

**Comment by DrAma999** [comment]
Thank you Jonathan fixed for En locale, but in Italian the problem persists

**Comment by eniPay** [comment]
Device Vertical
![img_2137](https://cloud.githubusercontent.com/assets/13024192/9085905/df20f2b8-3b78-11e5-8429-f32a148d0c48.PNG)

Simulator Vertical
![screen shot 2015-08-05 at 13 49 30](https://cloud.githubusercontent.com/assets/13024192/9085878/ab93ff4e-3b78-11e5-8112-134d0f849be9.png)

Device Selection
![img_2138](https://cloud.githubusercontent.com/assets/13024192/9085903/dd78b5b8-3b78-11e5-987b-f6600a23519f.PNG)

Simulator Selection
![screen shot 2015-08-05 at 13 49 18](https://cloud.githubusercontent.com/assets/13024192/9085877/ab06daf6-3b78-11e5-8469-6cb4524ae5c5.png)

Hi Jonathan, I believe the problem is for devices only (regardless of locale). These are screenshots running from the latest commit, and the days are all correct for the simulator but wrong for devices (maybe something to do with the week start date?).
I've looked for the bug myself but can't find it, hopefully this can help you.

Cheers,

Dylan

**Comment by jonathantribouharet** [comment]
Fixed.
