### ISSUE TITLE
add and remove selected date

### ISSUE THREAD

**Issue by jeffreyliu8** [jonathantribouharet/JTCalendar#193]
Hi, thank you for your great library. I just a few questions.

How to add a selected date(s) dynamically, not with touch, and how to remove it? (not the little dots)

**Comment by jonathantribouharet** [comment]
If you use the same king of implementation of selection than in `SelectionViewController` (in the example project), you have to do

	[_datesSelected addObject:yourDate];

	// Or

	[_datesSelected removeObject:yourDate];


	// For reload visible (left, center and right) page
	[_calendarManager reload];


This works because of the implementation of `- (void)calendar:(JTCalendarManager *)calendar prepareDayView:(JTCalendarDayView *)dayView`

	// Selected date
	else if([self isInDatesSelected:dayView.date]){
	    dayView.circleView.hidden = NO;
	    dayView.circleView.backgroundColor = [UIColor redColor];
	    dayView.dotView.backgroundColor = [UIColor whiteColor];
	    dayView.textLabel.textColor = [UIColor whiteColor];
	}


The selection system is now extern to the library, because a lot of people wanna do different things and I cannot provide a simple system extensible enough. So I just provide an example of implementation.

**Comment by jeffreyliu8** [comment]
Thank you, this is very helpful information
