### ISSUE TITLE
Dots are clipped in different sides.

### ISSUE THREAD

**Issue by Hardenn** [jonathantribouharet/JTCalendar#198]
![ios simulator - resizable iphone - resizable iphone ios 8 4 12h141 2015-08-24 11-44-14](https://cloud.githubusercontent.com/assets/1327323/9436088/95fba24a-4a55-11e5-864e-024de6008545.png)

**Comment by Hardenn** [comment]
I could resolve it using:

dayView.dotView.layer.rasterizationScale = [UIScreen mainScreen].scale;
dayView.dotView.layer.shouldRasterize = YES;

But now circles are not smooth.

**Comment by jonathantribouharet** [comment]
What do you mean by not smooth?
I had the same problem and on the previous version of the calendar I created a class `JTCircleView` https://github.com/jonathantribouharet/JTCalendar/blob/1.x/JTCalendar/JTCircleView.m.

The problem was similar to http://stackoverflow.com/questions/17038017/ios-draw-filled-circles.

I had your code in the next released.

**Comment by Hardenn** [comment]
Now dots are some kind of blurred and fuzzy (after rasterization).
But it's not so notable and better than was.

Thanks for bugfix!
