### ISSUE TITLE
Calendar doesn't refresh its layout after splitViewController:willChangeToDisplayMode

### ISSUE THREAD

**Issue by apple64** [jonathantribouharet/JTCalendar#56]
Hi and thanks for this great calendar.

It seems that there is no layout refresh after splitViewController:willChangeToDisplayMode. Even with [self.calendar reloadAppearance] the calendar doesn't refresh its appearance and the result is not the desired one.

![2015-02-09 13 39 34](https://cloud.githubusercontent.com/assets/10921649/6105563/20316be6-b061-11e4-91e7-bc4d0839e045.png)

Thanks in advance!

**Comment by athulgrg** [comment]
Had the same issue here... it was on rotation...

**Comment by jonathantribouharet** [comment]
I just add in the last version of the README how to do it. Just call

     [self.calendar updatePage];

in `didRotateFromInterfaceOrientation` in your controller for manage the rotation.

**Comment by apple64** [comment]
It does't solve my issue. It fixes the rotation problem but not the splitViewController:willChangeToDisplayMode.

It seems that self.contentView.frame in -repositionViews has always the wrong (opposite) value.
In didRotateFromInterfaceOrientation the value is correct.

**Comment by jonathantribouharet** [comment]
I never use UISplitViewController, but it s normal it doesn't work in `willChangeToDisplayMode` because `updatePage` must be call after the view change. Whereas the `willChangeToDisplayMode` is before ('will' in the name), i don't know the name of the method for UISplitViewController, i think it is something like `primaryViewControllerForCollapsingSplitViewController` or `primaryViewControllerForExpandingSplitViewController`.

**Comment by jonathantribouharet** [comment]
Sorry, my mistake it's not `updatePage` you have to call but `repositionViews` and update to the latest version.
