### ISSUE TITLE
Delay when displaying calendar

### ISSUE THREAD

**Issue by axelkennedal** [jonathantribouharet/JTCalendar#70]
I've got a calendar set up and it's working fine except for that when it is displayed it first displays a previous month and then a very short moment later jumps to the correct month (the current date). This looks very bad and needs a fix. (Yes, I'm calling [self.calendar reloadData] from viewDidAppear)

**Comment by jonathantribouharet** [comment]
If you use Autolayout it reduce performance, in some case you can call `reloadData` in `viewWillAppear`.

**Comment by axelkennedal** [comment]
If I call it in viewWillAppear the calendar doesn't focus on the current date. Shouldn't it be constructed so that you prepare the calendar view and everything before viewDidAppear? Because at that point the view has appeared and any changes made after that are going to be visible to the user (instead of just preparing everything before the viewDidAppear) @jonathantribouharet

**Comment by jonathantribouharet** [comment]
The calendar is build when you do the `initWithFrame` or when it's created by Interface Builder but but position of the calendar is not set.
The problem is before `viewDidAppear` is called the width of the frame of the controller's view is not good (probably the default value 320), so the calendar's width neither and the contentOffset is based on the width of the calendar.
It's one of my biggest problem, I have to rewrite the library (inherit from UIScrollView instead of using delegate and not using the default page mechanism) for that but I don't have the time yet.

You can try to call `repositionViews` in `viewDidAppear` and call `reloadData` in `viewWillAppear`, I'm not sure about that.

**Comment by axelkennedal** [comment]
i think I might have found a simple solution! Just call reloadData in viewDidLayoutSubviews instead! At the time it is called all of the dimensions and constraints should be known. Works for me at least! (Might be worth updating the documentation)

**Comment by DoctorG** [comment]
This is a good practice anyway.  Many times if you are changing anything RE the final size the view in a VC you must do it in viewDidLayoutSubviews not viewDidLoad or viewWillAppear.

**Comment by jonathantribouharet** [comment]
Ok thanks,I will test and update the documentation.
