### ISSUE TITLE
Add Left and Right Arrows Button

### ISSUE THREAD

**Issue by ankitgoyalapplify** [jonathantribouharet/JTCalendar#87]
Hello,

Can you please describe how can we add left and right buttons on the calendar. So that we can get the functionality on button click too.

**Comment by jonathantribouharet** [comment]
You create two buttons, like any buttons, and you call `loadPreviousMonth` or loadNextMonth` method.

**Comment by ankitgoyalapplify** [comment]
Hello,

I have already tried this but It did not help. Can you please provide a little bit of code for the same. I shall be very thankful to you.

**Comment by jonathantribouharet** [comment]
Sorry, but it can't be more simple to explain, create two buttons and on the TouchUpInside event call `[self.calendar loadPreviousMonth]`.

**Comment by ankitgoyalapplify** [comment]
Hello,

Thank you so much jonathantribouharet. It really worked. Thanks :)

**Comment by beulahpt** [comment]
Hi,

I want to show arrows instead of labels. 

If I set _calendarMenuView.contentRatio = 0.5, the left and right labels with month name are visible. I tried without setting contentRatio. But the buttons are not clickable. Any help here?

![Screenshot 2020-10-24 at 5 24 44 PM](https://user-images.githubusercontent.com/57248044/97081111-e1050f80-161d-11eb-918f-2becb830e42d.png)
